# Generated by Django 2.1.2 on 2018-11-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20181101_0926'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrelation',
            unique_together={('to_user', 'from_user')},
        ),
    ]
