# Generated by Django 2.1.2 on 2018-10-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='comment',
            name='_html',
            field=models.TextField(blank=True),
        ),
    ]
